### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by addania** [addania/challenge#17]
- [x] Change appropriate base for each PR

- [x] Merge first 4 PRs
   - [x] 1st

   - [x] 2nd

   - [x] 3rd

   - [x] 4th

- [x] Rework https://github.com/addania/challenge/pull/13 with following:

   - [x] Remove unnecessary assignments (return values directly)

   - [ ] ~~Remove function definitions within functions (for example in: .map, .forEach) - .map and .forEach are not on 04Branch (they are later on on 03Branch - the last one)~~

   - [x] Rename option functions for corresponding Highchart or filter

   - [x] Rename message in Highcharts options to something more meaningful as a title

   - [x] Use time series, instead of categories for Highcharts

   - [x] Remove repeating code (for example in filter if(apply)...)

   - [x] Output dictionaries instead of arrays where appropriate

      - [x] calculateAggregates.js

   - [x] Remove commented out code and all console logs

   - [x] Provide whole set to Highcharts instead of only an array

   - [x] improve naming

   - [x] shorten code - currently - 86 rows

   - [x] check tests
